name: "ðŸš€ ðŸŸ¢ Npm Publish"

# on:
#     push:
#       branches: [ main ]
on: [push, pull_request]

jobs:
    release:
        name: ðŸš€ Npm Publish
        runs-on: ubuntu-latest
        if: "startsWith(github.event.head_commit.message, 'Publish')"
        strategy: 
          matrix:
            node-version: [15.x]
        steps:
        - uses: actions/checkout@v2
        - name: ðŸŸ¢ Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: 'https://registry.npmjs.org'
            token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}


        - name: Add type definitions
          run: npm i --save-dev @types/node
          working-directory: ./

        - name: Install golang dependencies
          run: go get github.com/Danny-Dasilva/CycleTLS/cycletls
          working-directory: ./
        
        - name: Install deps
          run: npm install --unsafe-perm
          working-directory: ./

        

        - name: set name
          run: git config --global user.name 'Danny-Dasilva'
        - name: set email
          run: git config --global user.email 'secrets.EMAIL'
        - name: bump version
          run: npm version patch -m "Release"
          working-directory: ./my-package
        - name: Push git
          working-directory: ./my-package
          run: git commit -a -m "Release" && git push


      

        - name: ðŸš€ Publish
          run: npm publish
          working-directory: ./
          env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}