name: "ðŸš¨ ðŸŸ¢ Npm Test publish"

on: [push, pull_request]

jobs:
    release:
        name: test npm publish
        runs-on: ubuntu-latest
        strategy: 
          matrix:
            node-version: [15.x]
        steps:
        - uses: actions/checkout@v2
        - name: ðŸŸ¢ Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
            registry-url: 'https://registry.npmjs.org'

        - name: Set up Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}

        # - name: Add type definitions
        #   run: npm i --save-dev
        #   working-directory: ./
        - name: Install golang dependencies
          run: go get github.com/Danny-Dasilva/CycleTLS/cycletls
          working-directory: ./

        - name: Add type definitions
          run: npm i
          working-directory: ./


        - name: ðŸš€ publish
          run: npm publish --dry-run
          working-directory: ./