name: "ðŸš¨ ðŸš€ ðŸŸ¢ Npm Test Publish Package"

on: [pull_request]

jobs:
  release:
    name: Test Npm Publish
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        go-version: ['1.21']
    steps:
      - uses: actions/checkout@v4
      - name: ðŸŸ¢ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Export Go
        run: go env -w  GO111MODULE=auto
        working-directory: ./

      - name: Install golang all deps
        run: while read l; do go get -v "$l"; done < <(go list -f '{{ join .Imports "\n" }}' ./cycletls)
        shell: bash

      - name: Install npm depencencies
        run: npm ci --unsafe-perm

        working-directory: ./

      - name: ðŸš€ publish
        run: npm publish --dry-run
        working-directory: ./
