name: "ðŸš¨ ðŸŸ¢ Npm Test Publish Package"

on: [pull_request]

jobs:
  release:
    name: test npm publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.16]
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: ðŸŸ¢ Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Export Go
        run: go env -w  GO111MODULE=auto
        working-directory: ./
      - name: Install golang dependencies
        run: go get github.com/Danny-Dasilva/CycleTLS/cycletls && go get gitlab.com/yawning/utls.git
        working-directory: ./

      - name: Install npm depencencies
        run: npm ci
        working-directory: ./

      - name: ðŸš€ publish
        run: npm publish --dry-run
        working-directory: ./
